name: Update Data
on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: iffy/install-nim@v5
      - run: nimble install -y puppy
      - run: nim c src/main.nim
      - run: ./src/main
      - name: Push updates
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add README.md LOCAL_MODELS.md CATEGORIES.md data/registry.json
          git commit -m "update: $(date -u)" || exit 0
          git push
